# fly.toml app configuration file generated for bitter-violet-8097 on 2023-06-23T11:32:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bitter-violet-8097"
primary_region = "sea"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

